apiVersion: v1
kind: Service
metadata:
  name: {{ template "owhois.fullname" . }}
  labels:
    app: {{ template "owhois.name" . }}
    chart: {{ template "owhois.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4343
      protocol: TCP
  selector:
    app: {{ template "owhois.name" . }}
    release: {{ .Release.Name }}
