#!/bin/sh
set -e

mkdir -p data/iana
curl -f -s -S https://www.iana.org/assignments/ipv4-address-space/ipv4-address-space.csv > data/iana/ipv4-address-space.csv
curl -f -s -S https://www.iana.org/assignments/ipv6-unicast-address-assignments/ipv6-unicast-address-assignments.csv > data/iana/ipv6-unicast-address-assignments.csv
curl -f -s -S https://www.iana.org/assignments/as-numbers/as-numbers-1.csv > data/iana/as-numbers-1.csv
curl -f -s -S https://www.iana.org/assignments/as-numbers/as-numbers-2.csv > data/iana/as-numbers-2.csv

mkdir -p data/afrinic
curl -f -s -S http://ftp.afrinic.net/pub/stats/afrinic/delegated-afrinic-extended-latest > data/afrinic/delegated-afrinic-extended-latest

mkdir -p data/apnic
curl -f -s -S http://ftp.apnic.net/pub/stats/apnic/delegated-apnic-extended-latest > data/apnic/delegated-apnic-extended-latest

mkdir -p data/arin
curl -f -s -S http://ftp.arin.net/pub/stats/arin/delegated-arin-extended-latest > data/arin/delegated-arin-extended-latest

mkdir -p data/lacnic
curl -f -s -S http://ftp.lacnic.net/pub/stats/lacnic/delegated-lacnic-extended-latest > data/lacnic/delegated-lacnic-extended-latest

mkdir -p data/ripe
curl -f -s -S http://ftp.ripe.net/pub/stats/ripencc/delegated-ripencc-extended-latest > data/ripe/delegated-ripencc-extended-latest
